export const UPDATE_PLAYER_NUMBER = "UPDATE_PLAYER_NUMBER";
export const ADD_PLAYER_TEAM = "ADD_PLAYER_TEAM";
export const UPDATE_TEAMS = "UPDATE_TEAMS";
export const UPDATE_PLAYER_BY_IDX = "UPDATE_PLAYER_BY_IDX";
